name: liderfacilites
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_auth: ^0.15.4
  cloud_firestore: ^0.13.2+1
  shared_preferences: ^0.5.6+1
  firebase_storage: ^3.1.1
  image_picker: ^0.6.3+1
  provider: ^4.0.4
  google_maps_flutter: ^0.5.24+1
  geolocator: ^5.3.0
  geocoder: ^0.2.1
  fluttertoast: ^3.1.3
  cached_network_image: ^2.0.0
  flutter_rating_bar: ^3.0.1+1
  credit_card_number_validator: ^1.0.4
  google_sign_in: ^4.1.4
  http: ^0.12.0+4
  flutter_facebook_login: ^3.0.0
  stripe_payment: ^1.0.6


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lang/en.json
    - lang/pt.json
    - assets/images/placeholder.jpg
    - assets/images/logo.png
    - assets/images/mastercard.png
    - assets/images/visa.png
    - assets/images/account.png
    - assets/images/noservice.png
    - assets/images/location.png
    - assets/images/mylocation.png
    - assets/images/booking.png
    - assets/icons/health.png
    - assets/icons/repair.png
    - assets/icons/cleaning.png
    - assets/icons/car.png
    - assets/icons/electrical.png
    - assets/icons/music.png
    - assets/icons/hydraulic.png
    - assets/icons/biker.png
    - assets/icons/locksmith.png
    - assets/icons/eldercare.png
    - assets/icons/photographer.png
    - assets/icons/gardner.png
    - assets/icons/carwash.png
    - assets/icons/pets.png
    - assets/icons/manicure.png
    - assets/icons/food.png
    - assets/icons/automobile.png
    - assets/icons/maintanance.png
    - assets/icons/ac.png
    - assets/icons/fa.png
    - assets/icons/technicalassistance.png
    - assets/icons/massage.png
    - assets/icons/personaltrainer.png
    - assets/icons/kidparty.png
    - assets/icons/glass.png
    - assets/icons/reform.png
    - assets/icons/freight.png

    - assets/icons/selectedtypes/cleanings.png
    - assets/icons/selectedtypes/cars.png
    - assets/icons/selectedtypes/electricals.png
    - assets/icons/selectedtypes/musics.png
    - assets/icons/selectedtypes/hydraulics.png
    - assets/icons/selectedtypes/bikers.png
    - assets/icons/selectedtypes/locksmiths.png
    - assets/icons/selectedtypes/eldercares.png
    - assets/icons/selectedtypes/photographers.png
    - assets/icons/selectedtypes/gardners.png
    - assets/icons/selectedtypes/carwashs.png
    - assets/icons/selectedtypes/petss.png
    - assets/icons/selectedtypes/manicures.png
    - assets/icons/selectedtypes/foods.png
    - assets/icons/selectedtypes/automobiles.png
    - assets/icons/selectedtypes/maintanances.png
    - assets/icons/selectedtypes/acs.png
    - assets/icons/selectedtypes/fas.png
    - assets/icons/selectedtypes/technicalassistances.png
    - assets/icons/selectedtypes/massages.png
    - assets/icons/selectedtypes/personaltrainers.png
    - assets/icons/selectedtypes/kidpartys.png
    - assets/icons/selectedtypes/glasss.png
    - assets/icons/selectedtypes/reforms.png
    - assets/icons/selectedtypes/freights.png

  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
